source "https://rubygems.org"

# This gem ensures your local environment matches GitHub Pages
gem "github-pages", group: :jekyll_plugins

# If you are using a specific theme like Minima, add it here:
gem "minima", "~> 2.5"

# Common plugins for SEO and Feeds
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end
